<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="unittest.loader._FailedTest-20250416145726" tests="1" file="unittest/loader.py" time="0.001" timestamp="2025-04-16T14:57:26" failures="0" errors="1" skipped="0">
	<testcase classname="unittest.loader._FailedTest" name="module" time="0.001" timestamp="2025-04-16T14:57:26" file="..\..\..\..\..\AppData\Local\Programs\Python\Python313\Lib\unittest\loader.py" line="32">
		<error type="ImportError" message="Failed to import test module: module&#10;Traceback (most recent call last):&#10;  File &quot;C:\Users\chaker\AppData\Local\Programs\Python\Python313\Lib\unittest\loader.py&quot;, line 137, in loadTestsFromName&#10;    module = __import__(module_name)&#10;ModuleNotFoundError: No module named 'module'&#10;"><![CDATA[ImportError: Failed to import test module: module
Traceback (most recent call last):
  File "C:\Users\chaker\AppData\Local\Programs\Python\Python313\Lib\unittest\loader.py", line 137, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'module'

]]></error>
	</testcase>
</testsuite>
